### ISSUE TITLE
Credit?

### ISSUE THREAD

**Issue by FoxIshDaBest** [PugFreedomMod/FreedomBot#1]
You have bypassed the "forked from RainbowFreedomDev/FreedomBot" that links to the original post. Any reasons why? Also, you downloaded then re uploaded all of the files.

@DUFCLiam 

If you don't want to credit me for my work, I will delete this repository from the PugFreedomMod organization.

**Comment by rovertdude** [comment]
@FoxIshDaBest 
If possible, I think I can see if I can find other ways to credit it.

**Comment by DUFCLiam** [comment]
I left the Copyright on the reader @FoxIsDaBest

**Comment by FoxIshDaBest** [comment]
Oh didn't see that @DUFCLiam. Sorry

**Comment by FoxIshDaBest** [comment]
And thanks @rovertdude for the update linking to the original repository.
